### ISSUE TITLE
FEATURE: Cow Death - kill off cows if health is low

### ISSUE THREAD

**Issue by briggsrr** [ucsb-cs156/proj-happycows#17]
# NEED TO UPDATE ISSUE: don't think we need all of these endpoints -> just need way to kill cows when health = 0 for the 'batch' (see batch issue)

# Feature Summary 
We want an admin to able run the Cow Health Update Job so that cows get killed off everytime the Cow Health Update job runs according to the logic outlined in step 3.

# Discussion

# NEED TO UPDATE ISSUE: don't think we need all of these endpoints 

Note that a backend entity called CowDeath and a new repository called CowDeathRepository exists:
- `CowDeath.java` is where the basic entity is created with variables id, commonsId, userId, ZonedDateTime, cowsKilled, and avgHealth
- `CowDeathRepository.java` is where the basic CRUD repo is

### Step 1 (20pts)
Add a CowDeathController with three routes:
- POST /api/cowdeath available only to admins, that allows the creation of a new CowDeath entity
- GET /api/cowdeath/bycommons available only to admins that takes a commons id, and lists all cow casualties for that commons.
- GET /api/cowdeath/byusercommons that takes a commonsId and a userId and lists all cow deaths for that user commons

### Step 2 (10pts) 
Add a new React component called CowDeathTable. It should be able to display a list of CowDeaths in the format returned by the GET endpoints above. Include fixtures, tests and a storybook entry. 

### Step 3 (20pts)
Inside the CowHealthUpdate job, add the cow killing logic explained below.
```
for each commons c { 
   for each usercommons uc in the commons c {
       int averageCowHealth  = uc.getAvgCowHealth() // assuming this is a percentage
       int numCowDeaths = 0;
       for (int i=0; i< uc.numCows(); i++) {
           int r = Math.random();
           if (r < averageCowHealth ) {
               numCowDeaths ++
           }
       }
       if (numCowDeaths > 0) {
          create a new CowDeath entity.
          set the user_id,  commons_id, cowsKilled, and avgHealth
          store the CowDeath entity.
          get the UserCommons for this user and commons
          decrease the number of cows for the user, and save the userCommons
       } 
    } // end for loop over usercommons
}   // end for loop over commons
````

# Acceptance Criteria

### Step 1 
- [ ] Test the implemented routes in the CowDeathController using Swagger UI, ensuring the proper functioning and correct response formats.
 - [ ] Perform local testing of each route with various input scenarios, confirming the expected responses and error handling.
 - [ ] Confirm unit tests and integration tests pass for the CowDeathController to confirm proper functionality and appropriate security constraints. Ensure they pass mutation testing.

### Step 2
- [ ] Manually test the CowDeathTable component by running the React application locally and ensuring it displays the list of CowDeaths correctly.
- [ ] Verify that the CowDeathTable component interacts correctly with the backend by fetching data from the GET endpoints implemented in Step 1.
- [ ] Confirm unit tests and integration tests for the CowDeathTable component pass. Ensure that they pass mutation testing,.

### Step 3
- [ ] Run the CowHealthUpdate job locally, observing console output or log files to confirm that the cow killing logic is being executed and cow deaths are being processed.
 - [ ] Check that the CowDeath entities are created and stored in the H2 database by querying the database directly or using an H2 console.
 - [ ] Confirm unit tests and integration tests for the updated CowHealthUpdate job, checking that the cow killing logic is executed correctly and the database is updated as expected. Ensure these tests pass mutation testing to validate.
 - [ ] Deploy the application to the QA environment using Dokku, and validate the functionality of the new feature.

# Implementation Todos

### Step 1 
- [ ] Implement a POST route /api/cowdeath in the CowDeathController that allows admin users to create a new CowDeath entity.
- [ ]  Implement a GET route /api/cowdeath/bycommons in the CowDeathController that allows admin users to retrieve cow casualties for a specific commons by providing a commonsId.
 - [ ] Implement a GET route /api/cowdeath/byusercommons in the CowDeathController that retrieves cow deaths for a specific user commons by providing a userId and a commonsId.
 - [ ]  Add appropriate security constraints to the routes ensuring that only admin users have access to these endpoints.

### Step 2
- [ ] Create a new React component called CowDeathTable that can display a list of CowDeaths in the format returned by the GET endpoints in Step 1.
 - [ ] Add tests for the CowDeathTable component to ensure it renders correctly and handles data as expected.
 - [ ] Add a storybook entry for the CowDeathTable component, showcasing its various states and behaviors.
 - [ ] Include fixtures for the CowDeathTable component to support testing and development.

### Step 3
- [ ] Modify the CowHealthUpdate job to include the cow killing logic as described in the provided code snippet.
- [ ] When there are cow deaths, create a new CowDeath entity, set the user_id, commons_id, cowsKilled, and avgHealth attributes, and store the entity in the database.
 - [ ] Update the UserCommons entity to decrease the number of cows for the affected user and save the updated entity.
- [ ] Ensure that the updated cow killing logic does not interfere with other aspects of the CowHealthUpdate job.

### Testing:
- [ ] Front end tests pass and there is adequate coverage
- [ ] Back end tests pass and there is adequate coverage

**Comment by pconrad** [comment]
Fixed #44
