### ISSUE TITLE
FEATURE: Milk The Cows - create mechanism for building player wealth

### ISSUE THREAD

**Issue by briggsrr** [ucsb-cs156/proj-happycows#19]
# Feature Summary 
We want an admin to able run the Milk The Cows Job so that when triggered cows are milked and each player's wealth is increased according to the logic in step 2. 

# Discussion

### Step 1 
Add frontend changes to allow admin to launch the milk the cows job. 

### Step 2 
controller logic: milkPrice * (cows * cowHealth) 

# Acceptance Criteria

- [ ] First thing that should be true when story is done.
- [ ] Second thing that should be true when story is done.

# Implementation Todos

Frontend:
- [ ] First thing that must be done in the frontend code.
- [ ] Second thing that must be done in the frontend code.

Backend:
- [ ] First thing that must be done in the backend code.
- [ ] Second thing that must be done in the backend code.

Testing:
- [ ] Front end tests pass and there is adequate coverage
- [ ] Back end tests pass and there is adequate coverage

**Comment by pconrad** [comment]
Fixed #44
