### ISSUE TITLE
BUG: Profits Table Overflow

### ISSUE THREAD

**Issue by briggsrr** [ucsb-cs156/proj-happycows#34]
# Summary

When the viewport is less than 1800px, the table on the user commons page overflows in it's container. 

## Expected Behavior

The profits table should shrink with its container. 

## Current / Observed Behavior

The table overflows on the common page. 

<img width="535" alt="Screen Shot 2023-05-17 at 5 59 15 PM" src="https://github.com/ucsb-cs156/proj-happycows/assets/53193453/7568ab75-6dcd-49c7-b0f4-ce1a24ba6778">

# Steps to Reproduce

1. Navigate any user commons page
2. Shrink your viewport to less than 1800px

**Comment by pconrad** [comment]
fixed #44
