### ISSUE TITLE
FEATURE: Create different formulas for degradation rate 

### ISSUE THREAD

**Issue by briggsrr** [ucsb-cs156/proj-happycows#37]
### Have you updated the title?

- [X] I have updated the issue's title.

### Discussion

We want the ability to experiment with different algorithms for the degradation rate for each commons. 

### Acceptance Criteria

- [ ] First thing that should be true when refactor is done.
- [ ] Second thing that should be true when refactor is done.

### Implementation Todos

Frontend:
- [ ] First thing that must be done in the frontend code.
- [ ] Second thing that must be done in the frontend code.

Backend:
- [ ] First thing that must be done in the backend code.
- [ ] Second thing that must be done in the backend code.

Testing:
- [ ] Front end tests pass and there is adequate coverage
- [ ] Back end tests pass and there is adequate coverage

**Comment by pconrad** [comment]
fixed #44
