### ISSUE TITLE
FEATURE: Adding toast message when running a job

### ISSUE THREAD

**Issue by briggsrr** [ucsb-cs156/proj-happycows#38]
# Feature Summary 
As an Admin, I want a toast notification to confirm that a job was initiated successfully, providing immediate feedback on the status of the job.

# Discussion

Due to the significant delay between the initiation of a job and its logging, we aim to implement a toast notification that will instantly inform the Admin that the job is running.

# Acceptance Criteria

- [ ] Upon successful initiation of a job, a toast notification appears on the Admin's screen.
- [ ] The toast notification accurately indicates that the job has been initiated and is running.

Testing:
- [ ] Front end tests pass and there is adequate coverage
- [ ] Back end tests pass and there is adequate coverage

**Comment by pconrad** [comment]
fixed #44
