### ISSUE TITLE
BUG: Admin jobs page locks up due to backend/database problems

### ISSUE THREAD

**Issue by vivianross06** [ucsb-cs156/proj-happycows#40]
### Summary

When there is a problem with the database, the Manage Jobs page locks up and becomes unusable.

### Expected Behavior

The Manage Jobs page should show some sort of error message to the user in response to database errors, or otherwise handle the problem in a way that is easier to debug.

### Current / Observed Behavior

When there is a problem with the database, the Manage Jobs page locks up. Nothing can be clicked or accessed.

### Steps to Reproduce

1. Log into Happy Cows as an Admin user.
2. Navigate to the Manage Jobs page.
3. If there is an issue with the backend, the Manage Jobs page will lock up within a few seconds of opening.

### Browser / Platform Info

Chrome, Safari

**Comment by pconrad** [comment]
Fixed in #64
