### ISSUE TITLE
FEATURE: Eliminate purchase notification popups

### ISSUE THREAD

**Issue by iain801** [ucsb-cs156/proj-happycows#48]
# User Story

* As a User (especially mobile)
* I can sell cows without seeing toast message pop up.
* So that I can sell cows more easily

### Discussion

Right now when selling many cows by spam-clicking, the screen floods with times "Cow sold!" popups:

<img width="440" alt="image" src="https://github.com/ucsb-cs156/proj-happycows/assets/1119017/3d813aca-43ed-46f0-8d7f-7876de83bbc9">

This is especially distracting on mobile, as the popups block the interface and buttons.

These toast message aren't adding any value for the user, so we should just eliminate them in the case where the
cow sale was successful.  The messages may still be useful if/when there is an error condition, but if the purchase
is successful, it will be reflected in the cow count and dollar amounts on the screen.

(The toast message is a leftover feature from before those numbers were being reliably displayed and updated... it was useful at the time, but isn't anymore.)

### Acceptance Criteria

- [ ] No Toast message is generated when selling cows.

**Comment by pconrad** [comment]
Or... even better... just eliminate the popups entirely, since the display already changes when you buy a cow to indicate that the cow was purchased.

The popups (toast notifications) aren't really needed unless there's a problem (e.g. insufficient funds, database error, etc.)
